### ISSUE TITLE
CMS fails to compile on OpenBSD 6.5/amd64

### ISSUE THREAD

**Issue by xenotrope** [reyk/cloud-agent#4]
LibreSSL 2.9.1 (released 2019-04-21) has made a breaking change that impacts cloud-agent's CMS library.

On a native OpenBSD 6.4/amd64 machine the header file "/usr/include/openssl/asn1.h" contains "#define" lines for M_ASN1_new_of() and M_ASN1_free_of(). On OpenBSD 6.5/amd64, these lines are removed, so trying to compile cloud-agent fails with an implicit declaration error:

cc -O2 -pipe -g -I/home/ansible/cloud-agent.git/cms/lib -I/home/ansible/cloud-agent.git/cms/lib/../lib -I/usr/src/lib/libcrypto/asn1 -I/usr/src/lib/libcrypto/evp -Wall  -MD -MP  -c cms_dd.c -o cms_dd.o
cms_dd.c:75:10: warning: implicit declaration of function 'M_ASN1_new_of' is invalid in C99 [-Wimplicit-function-declaration]
    dd = M_ASN1_new_of(CMS_DigestedData);
         ^
cms_dd.c:75:24: error: unexpected type name 'CMS_DigestedData': expected expression
    dd = M_ASN1_new_of(CMS_DigestedData);
                       ^
1 warning and 1 error generated.
*** Error 1 in /home/ansible/cloud-agent.git/cms/lib (<bsd.lib.mk>:39 'cms_dd.o': @cc -O2 -pipe -g -I/home/ansible/cloud-agent.git/cms/lib -...)

This prevents the CMS library from building. Proposed fix is to manually add these defines to "./cms/lib/cms.h" if the LibreSSL version is 2.9.0 or higher:

--- a/cms/lib/cms.h
+++ b/cms/lib/cms.h
@@ -80,6 +80,12 @@ DECLARE_ASN1_FUNCTIONS(CMS_ContentInfo)
 DECLARE_ASN1_FUNCTIONS(CMS_ReceiptRequest)
 DECLARE_ASN1_PRINT_FUNCTION(CMS_ContentInfo)

+#if LIBRESSL_VERSION_NUMBER >= 0x20900000L
+# define M_ASN1_new_of(type) (type *)ASN1_item_new(ASN1_ITEM_rptr(type))
+# define M_ASN1_free_of(x, type) \\
+ASN1_item_free(CHECKED_PTR_OF(type, x), ASN1_ITEM_rptr(type))
+#endif
+
#define CMS_SIGNERINFO_ISSUER_SERIAL    0
#define CMS_SIGNERINFO_KEYIDENTIFIER    1

This change may have been introduced in LibreSSL 2.9.0, but v2.9.1 is the version included in OpenBSD 6.5 and so has wider adoption.

**Comment by reyk** [comment]
Thanks. I created a pull request and I will ask a LibreSSL dev to double-check it.

https://github.com/reyk/cloud-agent/pull/5
